server:
  port: 7003

eureka:
  instance:
    hostname: eureka7003.com # eureka实例的主机名
  client:
    register-with-eureka: false # 不把自己注册到eureka上
    fetch-registry: false # 表示自己为注册中心
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/